#!/usr/bin/env python

# This is a fairly general proxy script; it accepts a URL of the form
#
#    proxy/proto/host/arg1/arg2..
#
# translates it into the URL
#
#    proto://host/arg1/arg2...
#
# fetches it, and returns the result.  It works with both GET and POST
# requests, but it only works with a predefined list of hosts given
# in the array "allowedHosts" below.

import urllib2
import cgi
import sys, os, re

allowedHosts = [ 'hail.nemac.org' ]

uri = re.sub(r'^.*proxy/', '', os.environ["REQUEST_URI"])

parts = uri.split('/')

proto = parts[0]
host = parts[1]
rest = '/'.join(parts[2:])

url = "%s://%s/%s" % (proto, host, rest)

if allowedHosts and not host in allowedHosts:
    print "Status: 502 Bad Gateway"
    print "Content-Type: text/plain"
    print
    print "This proxy does not allow you to access that location (%s)." % (host,)
    print

try:
    if os.environ["REQUEST_METHOD"] == "POST":
        length = int(os.environ["CONTENT_LENGTH"])
        headers = {"Content-Type": os.environ["CONTENT_TYPE"]}
        body = sys.stdin.read(length)
        r = urllib2.Request(url, body, headers)
        y = urllib2.urlopen(r)
    else:
        y = urllib2.urlopen(url)
    i = y.info()
    if i.has_key("Content-Type"):
        print "Content-Type: %s" % (i["Content-Type"])
    else:
        print "Content-Type: text/plain"
    print
    print y.read()
    y.close()

except Exception, E:
    print "Status: 500 Unexpected Error"
    print "Content-Type: text/plain"
    print 
    print "Some unexpected error occurred. Error text was:", E
